In [1]:
%pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\tkate\anaconda3\lib\site-packages (4.0.34)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# import the necessary packages you need

import pyodbc
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [3]:
server = 'dap-projects-database.database.windows.net'
database = 'dapDB'
username = 'dataAnalyst_LP2'
password = 'A3g@3kR$2y'

# Create the connection string
connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}"

In [4]:
# Establish the connection
conn = pyodbc.connect(connection_string)

In [5]:
# Define the SQL query
query = "SELECT * FROM dbo.LP2_Telco_churn_first_3000"

# Execute the query and fetch the data
cursor = conn.cursor()
cursor.execute(query)
data = cursor.fetchall()

In [6]:
data1 = pd.read_sql(query, conn)
data1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,False,True,False,1,False,None,DSL,False,...,False,False,False,False,Month-to-month,True,Electronic check,29.850000,29.850000,False
1,5575-GNVDE,Male,False,False,False,34,True,False,DSL,True,...,True,False,False,False,One year,False,Mailed check,56.950001,1889.500000,False
2,3668-QPYBK,Male,False,False,False,2,True,False,DSL,True,...,False,False,False,False,Month-to-month,True,Mailed check,53.849998,108.150002,True
3,7795-CFOCW,Male,False,False,False,45,False,None,DSL,True,...,True,True,False,False,One year,False,Bank transfer (automatic),42.299999,1840.750000,False
4,9237-HQITU,Female,False,False,False,2,True,False,Fiber optic,False,...,False,False,False,False,Month-to-month,True,Electronic check,70.699997,151.649994,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2209-XADXF,Female,False,False,False,1,False,None,DSL,False,...,False,False,False,False,Month-to-month,False,Bank transfer (automatic),25.250000,25.250000,False
2996,6620-JDYNW,Female,False,False,False,18,True,True,DSL,True,...,True,False,False,False,Month-to-month,True,Mailed check,60.599998,1156.349976,False
2997,1891-FZYSA,Male,True,True,False,69,True,True,Fiber optic,False,...,False,False,True,False,Month-to-month,True,Electronic check,89.949997,6143.149902,True
2998,4770-UEZOX,Male,False,False,False,2,True,False,Fiber optic,False,...,False,False,False,False,Month-to-month,True,Electronic check,74.750000,144.800003,False
2999,1A1:U3001038-RQOST,Male,False,True,True,19,True,False,No,None,...,None,None,None,None,Month-to-month,False,Mailed check,20.600000,414.950012,False

In [7]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        3000 non-null   object
 1   gender            3000 non-null   object
 2   SeniorCitizen     3000 non-null   bool
 3   Partner           3000 non-null   bool
 4   Dependents        3000 non-null   bool
 5   tenure            3000 non-null   int64
 6   PhoneService      3000 non-null   bool
 7   MultipleLines     2731 non-null   object
 8   InternetService   3000 non-null   object
 9   OnlineSecurity    2349 non-null   object
 10  OnlineBackup      2349 non-null   object
 11  DeviceProtection  2349 non-null   object
 12  TechSupport       2349 non-null   object
 13  StreamingTV       2349 non-null   object
 14  StreamingMovies   2349 non-null   object
 15  Contract          3000 non-null   object
 16  PaperlessBilling  3000 non-null   bool
 17  PaymentMethod     3000 non-null   object
 18  MonthlyCharges    3000 non-null   float64
 19  TotalCharges      2995 non-null   float64
 20  Churn             2999 non-null   object
dtypes: bool(5), float64(2), int64(1), object(13)
memory usage: 389.8+ KB

In [8]:
data2 = pd.read_csv("LP2_Telco-churn-last-2000.csv")
data2

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5600-PDUJF,Male,0,No,No,6,Yes,No,DSL,No,...,No,Yes,No,No,Month-to-month,Yes,Credit card (automatic),49.50,312.7,No
1,8292-TYSPY,Male,0,No,No,19,Yes,No,DSL,No,...,Yes,Yes,No,No,Month-to-month,Yes,Credit card (automatic),55.00,1046.5,Yes
2,0567-XRHCU,Female,0,Yes,Yes,69,No,No phone service,DSL,Yes,...,Yes,No,No,Yes,Two year,Yes,Credit card (automatic),43.95,2960.1,No
3,1867-BDVFH,Male,0,Yes,Yes,11,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.35,834.2,Yes
4,2067-QYTCF,Female,0,Yes,No,64,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,111.15,6953.4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
2039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
2040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
2041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
2042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [9]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2043 entries, 0 to 2042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        2043 non-null   object
 1   gender            2043 non-null   object
 2   SeniorCitizen     2043 non-null   int64
 3   Partner           2043 non-null   object
 4   Dependents        2043 non-null   object
 5   tenure            2043 non-null   int64
 6   PhoneService      2043 non-null   object
 7   MultipleLines     2043 non-null   object
 8   InternetService   2043 non-null   object
 9   OnlineSecurity    2043 non-null   object
 10  OnlineBackup      2043 non-null   object
 11  DeviceProtection  2043 non-null   object
 12  TechSupport       2043 non-null   object
 13  StreamingTV       2043 non-null   object
 14  StreamingMovies   2043 non-null   object
 15  Contract          2043 non-null   object
 16  PaperlessBilling  2043 non-null   object
 17  PaymentMethod     2043 non-null   object
 18  MonthlyCharges    2043 non-null   float64
 19  TotalCharges      2043 non-null   object
 20  Churn             2043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 335.3+ KB

In [10]:
#  concatenate data1 and data2 to form one data set 
df = pd.concat([data1, data2])
df.to_csv('train.csv')
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,False,True,False,1,False,None,DSL,False,...,False,False,False,False,Month-to-month,True,Electronic check,29.850000,29.85,False
1,5575-GNVDE,Male,False,False,False,34,True,False,DSL,True,...,True,False,False,False,One year,False,Mailed check,56.950001,1889.5,False
2,3668-QPYBK,Male,False,False,False,2,True,False,DSL,True,...,False,False,False,False,Month-to-month,True,Mailed check,53.849998,108.150002,True
3,7795-CFOCW,Male,False,False,False,45,False,None,DSL,True,...,True,True,False,False,One year,False,Bank transfer (automatic),42.299999,1840.75,False
4,9237-HQITU,Female,False,False,False,2,True,False,Fiber optic,False,...,False,False,False,False,Month-to-month,True,Electronic check,70.699997,151.649994,True
5,9305-CDSKC,Female,False,False,False,8,True,True,Fiber optic,False,...,True,False,True,True,Month-to-month,True,Electronic check,99.650002,820.5,True
6,1452-KIOVK,Male,False,False,True,22,True,True,Fiber optic,False,...,False,False,True,False,Month-to-month,True,Credit card (automatic),89.099998,1949.400024,False
7,6713-OKOMC,Female,False,False,False,10,False,None,DSL,True,...,False,False,False,False,Month-to-month,False,Mailed check,29.750000,301.899994,False
8,7892-POOKP,Female,False,True,False,28,True,True,Fiber optic,False,...,True,True,True,True,Month-to-month,True,Electronic check,104.800003,3046.050049,True
9,6388-TABGU,Male,False,False,True,62,True,False,DSL,True,...,False,False,False,False,One year,False,Bank transfer (automatic),56.150002,3487.949951,False

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5043 entries, 0 to 2042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5043 non-null   object
 1   gender            5043 non-null   object
 2   SeniorCitizen     5043 non-null   object
 3   Partner           5043 non-null   object
 4   Dependents        5043 non-null   object
 5   tenure            5043 non-null   int64
 6   PhoneService      5043 non-null   object
 7   MultipleLines     4774 non-null   object
 8   InternetService   5043 non-null   object
 9   OnlineSecurity    4392 non-null   object
 10  OnlineBackup      4392 non-null   object
 11  DeviceProtection  4392 non-null   object
 12  TechSupport       4392 non-null   object
 13  StreamingTV       4392 non-null   object
 14  StreamingMovies   4392 non-null   object
 15  Contract          5043 non-null   object
 16  PaperlessBilling  5043 non-null   object
 17  PaymentMethod     5043 non-null   object
 18  MonthlyCharges    5043 non-null   float64
 19  TotalCharges      5038 non-null   object
 20  Churn             5042 non-null   object
dtypes: float64(1), int64(1), object(19)
memory usage: 866.8+ KB